"""update ans cre nullable

Revision ID: 0e0b4f0cc223
Revises: 1e87ec6766da
Create Date: 2024-09-05 11:20:38.244666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e0b4f0cc223'
down_revision: Union[str, None] = '1e87ec6766da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flashcards', 'answer_criteria_1',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('flashcards', 'answer_criteria_2',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('flashcards', 'answer_criteria_3',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flashcards', 'answer_criteria_3',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('flashcards', 'answer_criteria_2',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('flashcards', 'answer_criteria_1',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
