"""update flashcard and review

Revision ID: 1e87ec6766da
Revises: 10a3bffd06b4
Create Date: 2024-09-05 11:17:50.351809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e87ec6766da'
down_revision: Union[str, None] = '10a3bffd06b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flashcard_reviews', sa.Column('passed_criteria_1', sa.Boolean(), nullable=True))
    op.add_column('flashcard_reviews', sa.Column('passed_criteria_2', sa.Boolean(), nullable=True))
    op.add_column('flashcard_reviews', sa.Column('passed_criteria_3', sa.Boolean(), nullable=True))
    op.add_column('flashcards', sa.Column('expected_answer', sa.String(), nullable=True))
    op.add_column('flashcards', sa.Column('answer_criteria_1', sa.String(), nullable=False))
    op.add_column('flashcards', sa.Column('answer_criteria_2', sa.String(), nullable=False))
    op.add_column('flashcards', sa.Column('answer_criteria_3', sa.String(), nullable=False))
    op.drop_column('flashcards', 'review_criteria')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flashcards', sa.Column('review_criteria', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('flashcards', 'answer_criteria_3')
    op.drop_column('flashcards', 'answer_criteria_2')
    op.drop_column('flashcards', 'answer_criteria_1')
    op.drop_column('flashcards', 'expected_answer')
    op.drop_column('flashcard_reviews', 'passed_criteria_3')
    op.drop_column('flashcard_reviews', 'passed_criteria_2')
    op.drop_column('flashcard_reviews', 'passed_criteria_1')
    # ### end Alembic commands ###
