"""remove qty

Revision ID: 247e41b02bda
Revises: 5f915c0a4158
Create Date: 2024-09-02 16:19:45.302257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '247e41b02bda'
down_revision: Union[str, None] = '5f915c0a4158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_items_qty', table_name='items')
    op.drop_column('items', 'qty')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('qty', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix_items_qty', 'items', ['qty'], unique=False)
    # ### end Alembic commands ###
