"""update flashcard

Revision ID: 88fbf8e79899
Revises: 47b9bd0f5c99
Create Date: 2024-09-10 06:26:12.408589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88fbf8e79899'
down_revision: Union[str, None] = '47b9bd0f5c99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flashcards', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flashcards', 'created_at')
    # ### end Alembic commands ###
